.TH ubuntu-kylin-wizard "1" "09 August 2016" "" "Linux User's Manual"

.SH NAME
ubuntu-kylin-wizard \- setup wizard for Ubuntu/Ubuntu Kylin

.SH SYNOPSIS
.B ubuntu-kylin-wizard
.RI [ options ]
.br

.SH DESCRIPTION
The \fBubuntu-kylin-wizard\fP provides a friendly guide when user first logs in, and show them some basic information about the launcher, dash, indicators, control center, and so on.

.SH OPTIONS
.TP
.BR \-\-debug
Runs ubuntu-kylin-wizard under
.B gdb
and prints a stack trace on crash.

.TP
.BR \-h ", " \-\-help
Prints a usage message and exits.

.SH "SEE ALSO"
.B ubuntu-kylin-docs
(1)
